import ErrorHandler from '../utils/error_handler.js';

const PROVIDER_METHOD = {
    image: 'generateImage',
    video: 'generateVideo',
    tts: 'generateAudio',
    music: 'generateMusic'
};

const MEDIA_INSTRUCTIONS_TEMPLATE = `ATTENTION: this is NOT a request to generate {media_type} — the {media_type} was already generated by the system.
User: {username}
User's original description: "{description}"
The {media_type} is available at this URL: {media_url}

DO NOT tell the user to use {command}.
You MUST include the exact URL {media_url} verbatim in your response. Do not alter, truncate, or omit it.
Always place the URL with spaces around it if mid-sentence, flowing directly into the punchline's first word without punctuation or backticks touching it.
Speak in first person, as if you're presenting your {media_type} to the user. Keep it shorter than usual (<=30 words), smoothly integrating the URL.
Avoid phrases like "I made this for you", rather focus on the description and subject matter of the {media_type} itself.
Vary your openers — you might hint at the process, drop a reaction, or throw shade before revealing the link.
End with a one-line punchline riffing on one detail from the user's description, ensuring each sign-off feels unique.
Double-check: The URL {media_url} must appear exactly as-is in your response, with no punctuation or backticks touching it.`;

function resolveUsername(user) {
    if (!user) return 'someone';
    if (typeof user === 'string') return user;
    return user['display-name'] || user.username || user.name || 'someone';
}

function byteLength(value) {
    return value?.byteLength ?? value?.length ?? 0;
}

function displayMediaType(mediaType) {
    return mediaType === 'tts' ? 'TTS audio' : mediaType;
}

function buildMediaInstruction(username, prompt, mediaUrl, mediaType, command) {
    const description = String(prompt || '')
        .replace(/https?:\/\/\S+/g, '[original-url]')
        .replace(/\s+/g, ' ')
        .trim();

    const values = {
        media_type: mediaType,
        username,
        description,
        media_url: mediaUrl,
        command: command || ''
    };

    return MEDIA_INSTRUCTIONS_TEMPLATE.replace(
        /\{([^}]+)\}/g,
        (_match, key) => values[key] ?? ''
    );
}

function extractText(result) {
    if (!result) return '';
    if (typeof result === 'string') return result;
    if (typeof result === 'object' && typeof result.text === 'string') return result.text;
    return '';
}

function isPresentationFailure(result, errorHandler) {
    if (!result) return true;
    if (typeof result === 'object') {
        if (result.blocked === true || result.safetyBlocked === true) return true;
        if (!result.text || !String(result.text).trim()) return true;
    }

    const text = extractText(result).trim();
    if (!text) return true;

    if (errorHandler && typeof errorHandler.getMessage === 'function') {
        const knownFailureKeys = [
            'GEMINI_EMPTY_RESPONSE',
            'CONTENT_BLOCKED',
            'UNKNOWN_ERROR',
            'POLLINATIONS_CONTENT_BLOCKED'
        ];

        for (const key of knownFailureKeys) {
            const msg = errorHandler.getMessage(key);
            if (msg && text === msg.trim()) return true;
        }

        const safetyFilterPrefix = errorHandler.getMessage('SAFETY_FILTER')?.split('{')?.[0]?.trim();
        if (safetyFilterPrefix && text.startsWith(safetyFilterPrefix)) {
            return true;
        }
    }

    return false;
}

function ensureExactUrl(text, url) {
    const value = String(text || '').trim();
    if (!value) return url;
    const withUrl = value.includes(url)
        ? value
        : `${value} ${url}`.trim();

    return withUrl
        .split(url)
        .join(` ${url} `)
        .replace(/\s+/g, ' ')
        .trim();
}

function fitReplyAroundUrl(replyText, url, maxLength = 499) {
    if (!replyText || replyText.length <= maxLength) {
        return replyText;
    }
    if (!url || !replyText.includes(url)) {
        return replyText.slice(0, maxLength);
    }
    if (url.length >= maxLength) {
        return url.slice(0, maxLength);
    }

    const urlIndex = replyText.indexOf(url);
    const prefix = replyText.slice(0, urlIndex).trim();
    const suffix = replyText.slice(urlIndex + url.length).trim();

    const neededSeparators = (prefix ? 1 : 0) + (suffix ? 1 : 0);
    const availableCommentary = maxLength - url.length - neededSeparators;
    if (availableCommentary <= 0) {
        return url;
    }

    let truncatedPrefix = '';
    let truncatedSuffix = '';

    if (suffix) {
        if (suffix.length >= availableCommentary) {
            truncatedSuffix = suffix.slice(0, availableCommentary).trim();
            truncatedPrefix = '';
        } else {
            truncatedSuffix = suffix;
            const remainingForPrefix = availableCommentary - truncatedSuffix.length - (prefix ? 1 : 0);
            if (remainingForPrefix > 0 && prefix) {
                truncatedPrefix = prefix.slice(0, remainingForPrefix).trim();
            }
        }
    } else if (prefix) {
        truncatedPrefix = prefix.slice(0, availableCommentary).trim();
    }

    const parts = [truncatedPrefix, url, truncatedSuffix].filter(Boolean);
    return parts.join(' ').trim();
}

export class MediaPipeline {
    constructor({
        provider,
        uploader,
        storage,
        aiEngine,
        aiOperations,
        errorHandler = new ErrorHandler(),
        emotes,
        onMediaSaved = () => {},
        providerName = 'pollinations',
        maxLength = 499,
        now = () => Date.now(),
        idFactory = () => `${Date.now()}-${Math.random().toString(36).slice(2, 8)}`
    } = {}) {
        this.provider = provider;
        this.uploader = uploader;
        this.storage = storage;
        this.aiEngine = aiEngine ?? aiOperations;
        this.errorHandler = errorHandler || new ErrorHandler();
        this.emotes = emotes;
        this.onMediaSaved = onMediaSaved;
        this.providerName = providerName;
        this.maxLength = maxLength;
        this.now = now;
        this.idFactory = idFactory;
    }

    async #saveEntry(entry) {
        if (this.storage && typeof this.storage.addMediaEntry === 'function') {
            try {
                await this.storage.addMediaEntry(entry);
            } catch (error) {
                console.error('[Media] Failed to persist media entry:', error);
            }
        }

        if (typeof this.onMediaSaved === 'function') {
            try {
                await this.onMediaSaved(entry);
            } catch (error) {
                console.error('[Media] Failed to notify media subscribers:', error);
            }
        }
    }

    async #presentMedia({ channel, username, prompt, mediaType, command, mediaUrl }) {
        const fallback = this.errorHandler.getMessage('MEDIA_FALLBACK_RESPONSE', {
            mediaType,
            username,
            url: mediaUrl
        });

        let presentation;
        try {
            const ephemeralContext = buildMediaInstruction(
                username,
                prompt,
                mediaUrl,
                displayMediaType(mediaType),
                command
            );

            const result = await this.aiEngine?.generate(
                `User requested: ${prompt}`,
                {
                    disableMultimedia: true,
                    channel,
                    ephemeralContext
                }
            );

            if (isPresentationFailure(result, this.errorHandler)) {
                presentation = fallback;
            } else {
                presentation = extractText(result).trim() || fallback;
            }
        } catch (error) {
            console.error('[Media] Presentation generation failed:', error);
            presentation = fallback;
        }

        let decorated = presentation;
        try {
            if (this.emotes && typeof this.emotes.decorateReply === 'function') {
                decorated = this.emotes.decorateReply(
                    channel,
                    presentation,
                    { maxLength: this.maxLength }
                ) || presentation;
            }
        } catch (error) {
            console.error('[Media] Reply decoration failed:', error);
        }

        let replyText = ensureExactUrl(decorated, mediaUrl);
        replyText = fitReplyAroundUrl(replyText, mediaUrl, this.maxLength);
        return replyText;
    }

    async synthesize({
        channel,
        user,
        prompt,
        mediaType,
        command
    }) {
        const username = resolveUsername(user);
        const cleanPrompt = typeof prompt === 'string' ? prompt.trim() : '';

        if (!cleanPrompt) {
            return {
                success: false,
                replyText: this.errorHandler.getMessage('MEDIA_PROMPT_REQUIRED', {
                    username,
                    mediaType
                }),
                mediaEntry: null
            };
        }

        try {
            const methodName = PROVIDER_METHOD[mediaType];
            if (!methodName || !this.provider || typeof this.provider[methodName] !== 'function') {
                throw new Error(`Unsupported media type: ${mediaType}`);
            }

            const generated = await this.provider[methodName](cleanPrompt);

            if (!generated?.buffer || byteLength(generated.buffer) === 0) {
                return {
                    success: false,
                    replyText: this.errorHandler.getMessage('MEDIA_NO_DATA', {
                        service: this.providerName,
                        mediaType
                    }),
                    mediaEntry: null
                };
            }

            const mediaUrl = await this.uploader.upload(generated.buffer, {
                mediaType,
                mimeType: generated.mimeType
            });

            const timestamp = this.now();
            const mediaEntry = {
                id: this.idFactory(),
                timestamp,
                channel,
                username,
                command,
                prompt: cleanPrompt,
                mediaUrl,
                mediaType
            };

            await this.#saveEntry(mediaEntry);

            const replyText = await this.#presentMedia({
                channel,
                username,
                prompt: cleanPrompt,
                mediaType,
                command,
                mediaUrl
            });

            return {
                success: true,
                replyText,
                mediaEntry
            };
        } catch (error) {
            console.error(`[Media] ${mediaType} synthesis failed:`, error);

            return {
                success: false,
                replyText: this.errorHandler.createErrorResponse(error),
                mediaEntry: null
            };
        }
    }
}

export default MediaPipeline;
